name: omnix_app
description: "Omnix - Sustainability Scanner for Electronics"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^2.6.0
  riverpod_annotation: ^2.6.0
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.0.0
  
  # Networking
  http: ^1.0.0
  
  # UI
  google_maps_flutter: ^2.0.0
  image_picker: ^1.0.0
  url_launcher: ^6.0.0
  just_audio: ^0.9.0
  cached_network_image: ^3.0.0
  shimmer: ^3.0.0
  
  # Utilities
  json_annotation: ^4.0.0
  intl: ^0.20.0
  google_fonts: ^8.0.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
